image:
  name: hashicorp/terraform:light

  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' 
    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' 
    - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'

variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform      

before_script:
  - terraform --version
  - terraform init
  - terraform fmt

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

      
plan:
  stage: plan
  script:
    - terraform plan -var-file="east_dev_vars.tfvars" -out=$PLAN
    - echo \`\`\`diff > plan.txt
    - terraform show -no-color ${PLAN} | tee -a plan.txt
    - echo \`\`\` >> plan.txt
    - sed -i -e 's/  +/+/g' plan.txt
    - sed -i -e 's/  ~/~/g' plan.txt
    - sed -i -e 's/  -/-/g' plan.txt
    - MESSAGE=$(cat plan.txt)
    
  artifacts:
    name: plan  
    paths:
      - $PLAN
  
#build:
#  stage: plan
#  script:
#    - terraform plan -out=$PLAN
#  artifacts:
#    name: plan
#    paths:
#      - $PLAN
  

apply:
  stage: apply
  script:
    - terraform apply -var-file="east_dev_vars.tfvars" -input=false $PLAN
 # dependencies:
 #   - build
  when: manual
  
destroy:
  stage: destroy
  script:
    - echo "Destroying resources"
    - terraform destroy -state=$STATE --auto-approve
  dependencies:
    - apply  
  when: manual
  
